name: SonarCloud Analysis

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    name: Analyze on SonarCloud
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3 # Actualizado a la última versión

    - name: Set up PHP
      uses: shivammathur/setup-php@v2 # Usa la última versión estable de esta acción
      with:
        php-version: '8.1' # Especifica la última versión de PHP, ajusta según necesidad
        tools: composer, phpunit # Opcional: Instala herramientas adicionales


    - name: SonarCloud Scan
      uses: SonarSource/sonarcloud-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      with:
        args: >
          -Dsonar.projectKey="Agregue su key"
          -Dsonar.organization="Agregue su key"
